name: Nightly Regression Test
on:
  workflow_dispatch: # run on request (no need for PR)
  schedule:
    - cron: "0 0 * * *" # Every day at 12:00 AM
defaults:
  run:
    shell: bash
jobs:
  nightly_regression_test:
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-11', 'ubuntu-20.04', 'windows-2019']
        python-version: ['3.7', '3.8', '3.9', '3.10']
    name: nightly regression test (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Installing python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: |
          pip install -e '.[default,tf,tfds]' pytest pytest-cov
      - name: Unit testing
        run: |
          pytest -v tests/unit/ --cov
          datum -h
      - name: Integration testing
        run: |
          pytest -v tests/integration/
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: ${{ matrix.os }}_Python-${{ matrix.python-version }}
