name: Nightly Regression Test
on:
  workflow_dispatch: # run on request (no need for PR)
  schedule:
    - cron: "0 15 * * 2-6" # Every day at 12:00 AM in Korea time
defaults:
  run:
    shell: bash
jobs:
  nightly_regression_test:
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-11', 'ubuntu-20.04', 'windows-2019']
        python-version: ['3.7', '3.8', '3.9', '3.10']
    name: nightly regression test (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Installing python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: |
          pip install -e '.[default,tf,tfds]' pytest pytest-html
      - name: Nightly regression testing
        run: |
          pytest -v --html=nightly_regression_test_report.html
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: report/nightly_regression_test_report.html
